# Generated by Django 6.0.5 on 2026-05-13 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=20, verbose_name='Номер автомобіля')),
                ('start_time', models.DateTimeField(verbose_name='Час початку')),
                ('end_time', models.DateTimeField(verbose_name='Час завершення')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна за годину')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна вартість')),
                ('status', models.CharField(choices=[('active', 'Активне'), ('cancelled', 'Скасоване'), ('completed', 'Завершене')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='parkings.parkingspace', verbose_name='Паркомісце')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='parkings.tariff', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-created_at'],
            },
        ),
    ]
