# Generated by Django 6.0.5 on 2026-05-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Активне'), ('checked_in', 'Авто на парковці'), ('cancelled', 'Скасоване'), ('completed', 'Завершене')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
