# Generated by Django 6.0.5 on 2026-05-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='access_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Токен доступу'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час в’їзду'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час виїзду'),
        ),
    ]
