# Generated by Django 6.0.5 on 2026-05-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_access_token_reservation_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фінальна вартість'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='overtime_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доплата за перевищення часу'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість бронювання'),
        ),
    ]
