# Generated by Django 6.0.5 on 2026-05-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_final_price_reservation_overtime_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Базову вартість оплачено'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='overtime_is_paid',
            field=models.BooleanField(default=False, verbose_name='Доплату оплачено'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='overtime_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплати доплати'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплати базової вартості'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_note',
            field=models.TextField(blank=True, verbose_name='Примітка щодо оплати'),
        ),
    ]
