# Generated by Django 6.0.5 on 2026-05-17 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0005_reservation_final_price_reservation_overtime_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=100, verbose_name='Токен доступу')),
                ('action', models.CharField(choices=[('scan', 'Перевірка QR-коду'), ('check_in', 'Підтвердження в’їзду'), ('check_out', 'Підтвердження виїзду')], max_length=20, verbose_name='Дія')),
                ('result', models.CharField(choices=[('allowed', 'Доступ дозволено'), ('denied', 'Доступ заборонено'), ('success', 'Успішно'), ('error', 'Помилка'), ('info', 'Інформація')], max_length=20, verbose_name='Результат')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата і час')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Виконав')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='reservations.reservation', verbose_name='Бронювання')),
            ],
            options={
                'verbose_name': 'Журнал доступу',
                'verbose_name_plural': 'Журнал доступу',
                'ordering': ['-created_at'],
            },
        ),
    ]
