# Generated by Django 6.0.5 on 2026-05-15 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Номерний знак')),
                ('year', models.PositiveIntegerField(verbose_name='Рік випуску')),
                ('vehicle_type', models.CharField(choices=[('car', 'Легковий автомобіль'), ('electric', 'Електромобіль'), ('motorcycle', 'Мотоцикл'), ('minibus', 'Мікроавтобус'), ('truck', 'Вантажний автомобіль'), ('other', 'Інше')], max_length=20, verbose_name='Тип транспорту')),
                ('color', models.CharField(choices=[('white', 'Білий'), ('black', 'Чорний'), ('gray', 'Сірий'), ('silver', 'Сріблястий'), ('red', 'Червоний'), ('blue', 'Синій'), ('green', 'Зелений'), ('yellow', 'Жовтий'), ('brown', 'Коричневий'), ('other', 'Інший')], max_length=20, verbose_name='Колір')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Фото автомобіля')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
                'ordering': ['brand', 'model'],
                'constraints': [models.UniqueConstraint(fields=('user', 'license_plate'), name='unique_vehicle_plate_per_user')],
            },
        ),
    ]
