# Generated by Django 6.0.5 on 2026-05-13 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва парковки')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Парковка',
                'verbose_name_plural': 'Парковки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва типу')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Тип паркомісця',
                'verbose_name_plural': 'Типи паркомісць',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер місця')),
                ('row', models.PositiveIntegerField(verbose_name='Ряд')),
                ('column', models.PositiveIntegerField(verbose_name='Колонка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='parkings.parkinglot', verbose_name='Парковка')),
                ('space_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='parkings.parkingspacetype', verbose_name='Тип місця')),
            ],
            options={
                'verbose_name': 'Паркомісце',
                'verbose_name_plural': 'Паркомісця',
                'ordering': ['parking_lot', 'row', 'column'],
                'constraints': [models.UniqueConstraint(fields=('parking_lot', 'number'), name='unique_space_number_per_parking'), models.UniqueConstraint(fields=('parking_lot', 'row', 'column'), name='unique_space_position_per_parking')],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна за годину')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='parkings.parkinglot', verbose_name='Парковка')),
                ('space_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='parkings.parkingspacetype', verbose_name='Тип місця')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифи',
                'ordering': ['parking_lot', 'space_type'],
                'constraints': [models.UniqueConstraint(fields=('parking_lot', 'space_type'), name='unique_tariff_per_parking_and_type')],
            },
        ),
    ]
